"""Training-time concretes: losses, adapters, metrics, hooks, loop."""
from .adapters import DetectionSampleAdapter, DetectionSampleAdapterConfig
from .artifacts import (
    DistributionArtifact,
    ErrorHistogramArtifact,
    MetronomeHitArtifact,
    PredictionHeatmapArtifact,
    RatioErrorHeatmapArtifact,
    RatioHitArtifact,
)
from .augmentations import (
    ConditioningJitter,
    ContextTruncation,
    EventDropout,
    EventInsertion,
    EventJitter,
    LargeTimeShift,
    MelFreqJitter,
    MelGainJitter,
    MelGaussianNoise,
    PartialAdvMetronome,
    PartialMetronome,
    SpecAugFreq,
    SpecAugTime,
    TimeStretch,
    build_exp45_post_augs,
)
from .hooks import (
    CheckpointHook,
    ConsoleLoggerHook,
    CurveSpec,
    MetricCurvesHook,
    MetricLoggerHook,
    PerEvalJsonHook,
)
from .loop import train
from .losses import (
    GaussianCELoss,
    GaussianCELossConfig,
    LogEmdLoss,
    LogEmdLossConfig,
    OnsetLoss,
    OnsetLossConfig,
)
from .metrics_onset import OnsetMetric, OnsetMetricConfig

__all__ = [
    "CheckpointHook",
    "ConditioningJitter",
    "ConsoleLoggerHook",
    "ContextTruncation",
    "CurveSpec",
    "MetricCurvesHook",
    "DetectionSampleAdapter",
    "DetectionSampleAdapterConfig",
    "DistributionArtifact",
    "ErrorHistogramArtifact",
    "EventDropout",
    "EventInsertion",
    "EventJitter",
    "LargeTimeShift",
    "MelFreqJitter",
    "MelGainJitter",
    "MelGaussianNoise",
    "MetricLoggerHook",
    "MetronomeHitArtifact",
    "GaussianCELoss",
    "GaussianCELossConfig",
    "LogEmdLoss",
    "LogEmdLossConfig",
    "OnsetLoss",
    "OnsetLossConfig",
    "OnsetMetric",
    "OnsetMetricConfig",
    "PartialAdvMetronome",
    "PartialMetronome",
    "PredictionHeatmapArtifact",
    "RatioErrorHeatmapArtifact",
    "RatioHitArtifact",
    "SpecAugFreq",
    "SpecAugTime",
    "TimeStretch",
    "build_exp45_post_augs",
    "train",
]
